[versions]
androidDesugarJdkLibs = "2.0.4"
androidGradlePlugin = "8.5.0-beta02"
androidTools = "31.5.0-beta02"
androidR8 = "8.4.21"
androidxActivity = "1.9.0"
androidxAnnotation = "1.8.0"
androidxAppcompat = "1.7.0-rc01"
androidxBenchmark = "1.3.0-alpha05"
androidxCompose = "1.7.0-alpha07"
androidxComposeMaterial3 = "1.3.0-alpha05"
androidxCore = "1.14.0-alpha01"
androidxCoreSplashscreen = "1.2.0-alpha01"
androidxDataStore = "1.1.1"
androidxLifecycle = "2.8.0"
androidxLintGradle = "1.0.0-alpha01"
androidxPoolingContainer = "1.0.0"
androidxProfileInstaller = "1.4.0-alpha01"
androidxTestCore = "1.6.0-beta01"
androidxTestEspresso = "3.6.0-beta01"
androidxTestExt = "1.2.0-beta01"
androidxTestRunner = "1.6.0-beta01"
androidxTracing = "1.3.0-alpha02"
androidxWearCompose = "1.4.0-beta01"
androidxWearWatchface = "1.3.0-alpha03"
androidxWindow = "1.3.0-rc01"
apiGuardian = "1.1.2"
circuit = "0.20.0"
detekt = "1.23.6"
googleAutoValue = "1.10.4"
gradleDependenciesSorter = "0.6"
guavaAndroid = "32.0.0-android"
horologist = "0.6.11"
keeper = "0.16.0"
kermit = "2.0.3"
kotlin = "2.0.0-RC2"
kotlinInject = "0.6.3"
kotlinxCollectionsImmutable = "0.3.7"
kotlinxCoroutines = "1.8.1-Beta"
kotlinxDatetime = "0.6.0-RC.2"
kotlinxSerialization = "1.6.3"
ksp = "2.0.0-RC2-1.0.20"
jacoco = "0.8.11"
jetbrainsCompose = "1.6.10-rc03"
junit4 = "4.13.2"
leakCanary = "3.0-alpha-4"
material3WindowSizeClassMultiplatform = "0.5.0"
okio = "3.9.0"
robolectric = "4.12.1"
roborazzi = "1.16.1"
sealedEnum = "0.7.0"
slackComposeLintChecks = "1.3.1"
sqldelight = "2.0.2"
testParameterInjector = "1.16"
turbine = "1.1.0"
wire = "5.0.0-alpha01"

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-r8 = { group = "com.android.tools", name = "r8", version.ref = "androidR8" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmark" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidxCompose" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
material3-windowSizeClass-multiplatform = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "material3WindowSizeClassMultiplatform" }
androidx-compose-materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxCompose" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-uiGeometry = { group = "androidx.compose.ui", name = "ui-geometry", version.ref = "androidxCompose" }
androidx-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxCompose" }
androidx-compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-uiUnit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "androidxCompose" }
androidx-compose-uiUtil = { group = "androidx.compose.ui", name = "ui-util", version.ref = "androidxCompose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-dataStore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "androidxDataStore" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lint-gradle = { group = "androidx.lint", name = "lint-gradle", version.ref = "androidxLintGradle" }
androidx-poolingContainer = { group = "androidx.customview", name = "customview-poolingcontainer", version.ref = "androidxPoolingContainer" }
androidx-profileInstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileInstaller" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-tracing = { group = "androidx.tracing", name = "tracing", version.ref = "androidxTracing" }
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "androidxWearCompose" }
androidx-wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "androidxWearCompose" }
androidx-wear-compose-uiToolingPreview = { group = "androidx.wear.compose", name = "compose-ui-tooling", version.ref = "androidxWearCompose" }
androidx-wear-watchface = { group = "androidx.wear.watchface", name = "watchface", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-client = { group = "androidx.wear.watchface", name = "watchface-client", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-complications-data = { group = "androidx.wear.watchface", name = "watchface-complications-data", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-complications-dataSource = { group = "androidx.wear.watchface", name = "watchface-complications-data-source", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-complications-rendering = { group = "androidx.wear.watchface", name = "watchface-complications-rendering", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-data = { group = "androidx.wear.watchface", name = "watchface-data", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-editor = { group = "androidx.wear.watchface", name = "watchface-editor", version.ref = "androidxWearWatchface" }
androidx-wear-watchface-style = { group = "androidx.wear.watchface", name = "watchface-style", version.ref = "androidxWearWatchface" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }
apiGuardian-api = { group = "org.apiguardian", name = "apiguardian-api", version.ref = "apiGuardian" }
circuit-retained = { group = "com.slack.circuit", name = "circuit-retained", version.ref = "circuit" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
google-autoValue-annotations = { group = "com.google.auto.value", name = "auto-value-annotations", version.ref = "googleAutoValue" }
guava-android = { group = "com.google.guava", name = "guava", version.ref = "guavaAndroid" }
horologist-composeLayout = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "horologist" }
jetbrains-compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "jetbrainsCompose" }
jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "jetbrainsCompose" }
jetbrains-compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "jetbrainsCompose" }
jetbrains-compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "jetbrainsCompose" }
jetbrains-compose-materialIconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "jetbrainsCompose" }
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "jetbrainsCompose" }
jetbrains-compose-runtime-saveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "jetbrainsCompose" }
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiGeometry = { group = "org.jetbrains.compose.ui", name = "ui-geometry", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiTestJunit4 = { group = "org.jetbrains.compose.ui", name = "ui-test-junit4", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiText = { group = "org.jetbrains.compose.ui", name = "ui-text", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiToolingPreview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiUnit = { group = "org.jetbrains.compose.ui", name = "ui-unit", version.ref = "jetbrainsCompose" }
jetbrains-compose-uiUtil = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "jetbrainsCompose" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
keeper-gradlePlugin = { group = "com.slack.keeper", name = "keeper", version.ref = "keeper" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kotlin-composeCompilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinInject-ksp = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlinInject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlinInject" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
leakCanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }
leakCanary-instrumentation = { group = "com.squareup.leakcanary", name = "leakcanary-android-instrumentation", version.ref = "leakCanary" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi-core =  { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose =  { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
sealedEnum-ksp = { group = "com.github.livefront.sealed-enum", name = "ksp", version.ref = "sealedEnum" }
sealedEnum-runtime = { group = "com.github.livefront.sealed-enum", name = "runtime", version.ref = "sealedEnum" }
slackComposeLintChecks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "slackComposeLintChecks" }
sqldelight-androidDriver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutinesExtensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitiveAdapters = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqldelight" }
sqldelight-sqliteDriver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
testParameterInjector-junit4 = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testParameterInjector" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

[plugins]
convention-androidApplication = { id = "com.alexvanyo.composelife.androidApplication", version = "unspecified" }
convention-androidApplicationCompose = { id = "com.alexvanyo.composelife.androidApplicationCompose", version = "unspecified" }
convention-androidApplicationJacoco = { id = "com.alexvanyo.composelife.androidApplicationJacoco", version = "unspecified" }
convention-androidApplicationKsp = { id = "com.alexvanyo.composelife.androidApplicationKsp", version = "unspecified" }
convention-androidApplicationTesting = { id = "com.alexvanyo.composelife.androidApplicationTesting", version = "unspecified" }
convention-androidLibrary = { id = "com.alexvanyo.composelife.androidLibrary", version = "unspecified" }
convention-androidLibraryCompose = { id = "com.alexvanyo.composelife.androidLibraryCompose", version = "unspecified" }
convention-androidLibraryJacoco = { id = "com.alexvanyo.composelife.androidLibraryJacoco", version = "unspecified" }
convention-androidLibraryKsp = { id = "com.alexvanyo.composelife.androidLibraryKsp", version = "unspecified" }
convention-androidLibraryRoborazzi = { id = "com.alexvanyo.composelife.androidLibraryRoborazzi", version = "unspecified" }
convention-androidLibraryTesting = { id = "com.alexvanyo.composelife.androidLibraryTesting", version = "unspecified" }
convention-androidTest = { id = "com.alexvanyo.composelife.androidTest", version = "unspecified" }
convention-detekt = { id = "com.alexvanyo.composelife.detekt", version = "unspecified" }
convention-kotlinMultiplatform = { id = "com.alexvanyo.composelife.kotlinMultiplatform", version = "unspecified" }
convention-kotlinMultiplatformCompose = { id = "com.alexvanyo.composelife.kotlinMultiplatformCompose", version = "unspecified" }
convention-mergeJacoco = { id = "com.alexvanyo.composelife.mergeJacoco", version = "unspecified" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleDependenciesSorter = { id = "com.squareup.sort-dependencies", version.ref = "gradleDependenciesSorter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
