[versions]
accompanist = "0.20.0"
androidDesugarJdkLibs = "1.1.5"
androidxActivity = "1.3.0"
androidxCore = "1.6.0"
androidxEspresso = "3.4.0"
androidxLifecycle = "2.3.1"
androidxTest = "1.1.3"
compose = "1.0.4"
junit4 = "4.13.2"
junit5 = "5.8.1"

[libraries]
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref ="androidDesugarJdkLibs" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-test = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTest" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit5-jupiter = { group = "org.junit.jupiter", name="junit-jupiter", version.ref = "junit5" }
junit5-vintageEngine = { group = "org.junit.vintage", name="junit-vintage-engine", version.ref = "junit5" }
